server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8081
          predicates:
            - Path=/orders/**

        - id: inventory-service
          uri: http://inventory-service:8082
          predicates:
            - Path=/inventory/**

        - id: payment-service
          uri: http://payment-service:8083
          predicates:
            - Path=/payments/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles:
        http.server.requests: 0.5,0.95,0.99
      percentiles-histogram:
        http.server.requests: true
