spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_db
    password: password

services:
  inventory:
    base-url: http://toxiproxy:18082
  payment:
    base-url: http://toxiproxy:18083
